export const employmentOfferLetterFields = [
  "candidateFullName",
  "companyName",
  "jobTitle",
  "startDate",
  "address",
  "salaryAmount",
  "commissionPercentage",
  "allowanceAmount",
  "issueDate"
];

export const generateEmploymentOfferLetter = (data) => `<div class="agreement-template">
  <h1 class="agreement-title">Employment Offer Letter</h1>
  <style>
    .highlight { font-weight: bold; }
  </style>
  <div class="agreement-body">
    <p>To the attention of <span class="highlight">${data.candidateFullName}</span></p>
    <p><span class="highlight">${data.companyName}</span> (the "Employer") is pleased to offer you the position of <span class="highlight">${data.jobTitle}</span>. We are confident that you will find this new opportunity challenging and that you will make a significant contribution to the success of our company. The conditions of our offer are as follows:</p>
    <h2>1. POSITION.</h2>
    <p>The Employer offers you a full-time position starting from <span class="highlight">${data.startDate}</span> at <span class="highlight">${data.address}</span>, India.</p>
    <h2>2. SCOPE OF WORK.</h2>
    <p>In this role, you will be required to:</p>
    <ul>
      <li>Manage information flow in a timely and accurate manner.</li>
      <li>Manage executives' calendars and set up meetings.</li>
      <li>Make travel and accommodation arrangements.</li>
      <li>Prepare weekly monthly or quarterly reports.</li>
      <li>Keeping up with office supply inventory.</li>
      <li>Take minutes during meetings.</li>
      <li>Screen and direct phone calls and distribute correspondence.</li>
      <li>Organize and maintain the office filing system.</li>
    </ul>
    <h2>3. COMPENSATION.</h2>
    <p>The annual starting salary for this position is INR <span class="highlight">${data.salaryAmount}</span> (Indian Rupees) to be paid monthly on the last day of each month. In addition to this salary, the following compensation is offered:</p>
    <ul>
      <li>Commission: <span class="highlight">${data.commissionPercentage}</span> of gross profits from new customers directly generated by the Employee.</li>
      <li>Bonus: Awarded at the Employer's discretion based on performance.</li>
      <li>Allowance: Monthly reimbursement up to INR <span class="highlight">${data.allowanceAmount}</span> (Indian Rupees) for phone and transportation expenses within India.</li>
      <li>Insurance: Employer-provided life and health insurance in compliance with local regulations.</li>
      <li>Provident Fund (PF) Contributions: The Employer will register the Employee with the Employees' Provident Fund Organization (EPFO) and make mandatory contributions.</li>
    </ul>
    <h2>4. ANNUAL LEAVE.</h2>
    <p>You will be entitled to twelve (12) days of paid annual leave per year. This entitlement will commence after you have completed 365 days of continuous service within the calendar year. Leave will be credited at the rate of one day for every twenty days of work performed during the previous calendar year.</p>
    <p>Either party may terminate this arrangement upon notice in writing to either party that complies with Indian labor laws and regulations.</p>
    <p>We look forward to having you join our team. If you have any questions, please do not hesitate to contact us.</p>
    <p>Issued on <span class="highlight">${data.issueDate}</span>.</p>


    <h2>SIGNED BY:</h2>
    <div class="signatures">
      <div class="signature-block" style="display: flex; justify-content: space-between; margin-top: 40px;">
        <div>
          <p>The Employer</p>
          <p>The Employee</p>
        </div>
        <div>
          <p>The Witness</p>
          <p>The Witness</p>
        </div>
      </div>
    </div>
    <p>The terms and conditions will be outlined in an "Employment Agreement", which will be provided to you upon acceptance of the offer.</p>
  </div>
</div>`;
