export const employeeHandbookFields = [
  "companyName",
  "hrManagerFullName",
  "date"
];

export const generateEmployeeHandbook = (data) => `<div class="agreement-template">
  <h1 class="agreement-title">Employee Handbook</h1>
  <style>
    .highlight { font-weight: bold; }
  </style>
  <div class="agreement-body">
    <p>To the attention of all employees,</p>
    <p>This handbook provides essential information about <span class="highlight">${data.companyName}</span> policies, procedures, and expectations during your employment. It outlines your rights, benefits, and responsibilities as an employee in India. We strive to create a positive work environment that promotes growth, teamwork, and mutual respect. Open communication and adherence to policies are crucial for a harmonious and productive workplace. Please read this handbook carefully to navigate your employment successfully and addressing concerns. Note that this handbook is not a contract and policies may be updated. We value your contribution, support your growth, and encourage you to reach out to <span class="highlight">${data.hrManagerFullName}</span> with any questions. We wish you a successful journey with us in achieving our shared goals.</p>
    <h2>1. EMPLOYMENT BASICS.</h2>
    <p>The employment relationship between the company and its employees is governed by the laws of India, including the Employment Act and other relevant legislation.</p>
    <p>Employment contract types: The company may engage employees under various types of employment contracts as prescribed by the Employment Act and other relevant laws. These contract types may include full-time, part-time, fixed-term, freelancer, intern, or other legally recognized arrangements.</p>
    <p>Equal opportunity employment: The company is committed to providing equal employment opportunities to all individuals, irrespective of their race, color, religion, sex, national origin, age, disability, or any other protected status recognized by the Employment Act and other applicable laws.</p>
    <p>Discrimination in any aspect of employment, including but not limited to recruitment, hiring, promotion, training, compensation, benefits, and termination, is strictly prohibited.</p>
    <p>Recruitment and selection process: The company follows a fair and transparent recruitment and selection process, adhering to the principles of equal opportunity employment. The process may include the following steps:</p>
    <p>a) Vacant positions will be advertised internally and/or externally, providing employees and external candidates an equal opportunity to apply.</p>
    <p>b) Applications will be reviewed based on the requirements outlined in the job posting. Qualified candidates will be selected for further assessment.</p>
    <p>c) Candidates may be required to undergo interviews, skills assessments, and other relevant evaluations to determine their suitability for the position.</p>
    <p>d) The final selection decision will be based on objective criteria, including qualifications, experience, skills, and cultural fit.</p>
    <p>The company conducts background checks on prospective employees in compliance with the Employment Act and applicable laws. These checks include verifying educational qualifications, employment history, and necessary legal clearances, with prior consent from candidates. Employees are encouraged to refer qualified candidates for open positions, enhancing the recruitment process. Referrals undergo evaluation based on the same criteria, ensuring fairness and equal opportunity.</p>
    <p>Attendance: Employees must adhere to the company's attendance policies and guidelines, ensuring regular and punctual attendance to meet business requirements and maintain an efficient work environment. Absences should be reported following established procedures. Excessive absenteeism or tardiness may result in disciplinary action, following company policies and applicable laws. The company is committed to upholding these employment basics, creating a fair and inclusive working environment. By adhering to these principles, the company aims to attract and retain talented individuals who contribute to its success and growth.</p>
    <h2>2. WORKPLACE POLICIES.</h2>
    <p>The company is dedicated to fostering a safe, respectful, and inclusive workplace. Our workplace policies aim to cultivate a positive culture, safeguard employee rights and well-being, and ensure adherence to India laws and regulations.</p>
    <p>Confidentiality and data protection: Employees must ensure the confidentiality of company information, including proprietary data, trade secrets, and customer information. Disclosure or use of such information without authorization is strictly forbidden. Compliance with relevant laws, including the Personal Data Protection Act (PDPA) of India, is necessary when handling personal data. The company's data protection policies and applicable laws must be followed for the collection, processing, and storage of personal data.</p>
    <p>Harassment and violence: The company strictly prohibits all forms of harassment, including sexual harassment, discrimination, bullying, or any behavior that creates an offensive work environment. Employees must treat each other with respect and professionalism. Any incidents of harassment should be immediately reported for investigation and resolution.</p>
    <p>The company has a zero-tolerance policy for workplace violence, including physical assaults, threats, or any behavior that jeopardizes employee safety. Employees must report any incidents or threats immediately to their supervisor or designated authority. The company will promptly investigate and take necessary actions to ensure employee safety.</p>
    <p>Workplace safety and health: Employees must comply with safety protocols, procedures, and guidelines to ensure a safe working environment. This includes following instructions, using personal protective equipment (PPE) when necessary, and reporting any hazards. Employees are responsible for preventing accidents and injuries by participating in safety programs and suggesting improvements. In emergencies, employees must follow the company's emergency response plans. This includes knowing evacuation procedures, emergency contacts, and assembly points. The company maintains a smoke-free workplace in compliance with India laws and regulations. Smoking is strictly prohibited on company premises, including designated smoking areas. The company also strictly prohibits the use, possession, sale, or distribution of illegal drugs or alcohol during working hours or on company premises. Violations of this policy may result in disciplinary action, including termination, and employees may be required to seek assistance through rehabilitation programs.</p>
    <h2>3. CODE OF CONDUCT.</h2>
    <p>The Code of Conduct sets ethical standards and professional behavior for employees in India. It emphasizes integrity, honesty, respect, and compliance with laws and regulations. By adhering to this code, we foster a positive work environment that values fairness, mutual respect, and professionalism.</p>
    <p>Dress code: Employees are expected to maintain a professional appearance and dress in a manner appropriate for their roles and the work environment. The company may establish specific guidelines regarding dress code and appearance, which employees are required to adhere to.</p>
    <p>Cyber security and digital devices: Employees should use company internet resources and personal cell phones responsibly, limiting personal use and avoiding disruptions to work and network security. Corporate email should be used professionally, with no sharing of sensitive information, following company guidelines. Caution and discretion should be exercised on social media platforms to protect the company's reputation and confidentiality. Employees should be familiar with and adhere to the company's policies on internet, cell phone, email, and social media usage.</p>
    <p>Conflict of interest: Employees are expected to act in the best interests of the company and avoid situations that create a conflict between their personal interests and those of the company. Employees should disclose any potential conflicts of interest to their supervisor or the appropriate authority.</p>
    <p>Employee relationships: Employees should maintain professional relationships with colleagues, avoiding romantic or personal relationships that may create conflicts of interest or impact the work environment. Any conflicts arising from personal relationships should be reported. Employees should not participate in or influence decisions involving hiring, promotion, or evaluation of relatives or close personal connections to prevent nepotism and favoritism.</p>
    <p>Workplace visitors: Visitors should follow all company policies and guidelines while on company premises. Employees are responsible for ensuring that their visitors comply with applicable rules and regulations.</p>
    <p>Solicitation and distribution: Solicitation and distribution of non-work-related materials on company premises, during work hours, or using company resources are prohibited unless approved by the appropriate authority.</p>
    <h2>4. COMPENSATION AND DEVELOPMENT.</h2>
    <p>We value our employees and are committed to recognizing their contributions through competitive compensation, performance management, and employee development.</p>
    <p>Compensation status: Employees will receive a competitive compensation package that reflects their skills, experience, and contributions. Compensation will be periodically reviewed to ensure market alignment and internal equity. Overtime work, if required, will be compensated in accordance with relevant laws and regulations.</p>
    <p>Payroll: The company will process payroll accurately and in a timely manner. Employees are responsible for providing accurate and up-to-date information related to their payroll, such as bank account details and tax-related information.</p>
    <p>Performance management: The company evaluates employee performance through a management system, providing feedback and conducting regular reviews. Managers set clear performance expectations and support professional growth. Performance evaluations may influence decisions on promotions, salary adjustments, and other employment matters.</p>
    <p>Managers lead and support employees by providing direction, setting goals, and offering feedback and coaching. They create a positive work environment, promote open communication, and encourage employee growth and development.</p>
    <p>Employee training and development: The company is committed to the growth and development of its employees. Training and development opportunities will be provided to enhance employees' skills, knowledge, and abilities. Employees are encouraged to take an active role in their professional development by participating in training programs, workshops, and other learning activities.</p>
    <h2>5. BENEFITS AND PERKS.</h2>
    <p>The company recognizes the importance of employee well-being and offers a range of benefits and perks to support their health and work-life balance.</p>
    <p>Employee health: The company provides access to health insurance and medical benefits to support employees' physical and mental well-being.</p>
    <p>Workers' compensation: In compliance with the Employment Act, the company offers workers' compensation coverage to provide financial protection in the event of work-related injuries or illnesses.</p>
    <p>Work from home: The company promotes flexible work arrangements and allows eligible employees to work remotely, providing them with the necessary tools and resources to effectively perform their duties.</p>
    <p>Employee expenses: Reasonable and approved work-related expenses, such as travel or training costs, may be reimbursed in accordance with company policies and procedures.</p>
    <p>Company cars: Certain positions may be eligible for a company-provided car for business-related travel, subject to specific guidelines and approvals.</p>
    <p>Parking: The company may provide parking facilities or allowances for employees working at designated locations, subject to availability and applicable policies.</p>
    <p>Company-issued equipment: Employees may be provided with necessary equipment, such as laptops or mobile devices, to support their job responsibilities. Proper usage and care of company-issued equipment are expected.</p>
    <h2>6. WORKING HOURS, PTO AND VACATION.</h2>
    <p>The company is committed to promoting work-life balance and ensuring that employees have the opportunity to take time off for rest, personal obligations, and family needs.</p>
    <p>Working hours: The standard working hours for full-time employees are forty (40) hours per week, in accordance with the Employment Act and other applicable laws. Breaks and meal periods will be provided as required by law. Part-time employees' working hours will be prorated based on their agreed-upon schedule.</p>
    <p>Paid time off (PTO): Employees are eligible for paid time off, which includes vacation and personal days, to be used for rest, relaxation, personal appointments, or other personal matters. The number of PTO days ranging from 15 to 20 days per year for at least three (3) months of employment and must be notified at least seven (7) days in advance before taking paid leave.</p>
    <p>Holidays: Employees will be granted paid time off for recognized public holidays in India as mandated by law. The specific holidays and the company's policies regarding holiday observance will be communicated to employees annually.</p>
    <p>Sick leave: Employees may be eligible for paid sick leave in the event of personal illness or injury. Additional leave or accommodations may be available for long-term illness or disability, in accordance with the Employment Act and other relevant laws. The Employer will be granted sick leave with pay upon informing the Employer before and providing a medical certificate to the Employer.</p>
    <p>Jury duty and voting: Employees summoned for jury duty or required to fulfill voting responsibilities will be granted the necessary time off as mandated by law. The company may require proper documentation for such absences.</p>
    <p>Parental leave: Employees may be entitled to parental leave, including maternity, paternity, and adoption leave, in accordance with the Employment Act and other applicable laws. Employees who have worked for more than twelve (12) months prior to the birth of a child are entitled to a maximum of sixteen (16) weeks of maternity leave for female employees, including a maximum of eight (8) weeks of paid maternity leave. Male employees are entitled to a maximum of two (2) weeks of paid paternity leave.</p>
    <h2>7. EMPLOYEE RESIGNATION AND TERMINATION.</h2>
    <p>We understand that the employment relationship may sometimes come to an end due to various reasons. We aim to ensure a fair and respectful approach to these situations, in compliance with the Employment Act and other applicable laws.</p>
    <p>Progressive discipline: The company follows a progressive discipline approach, which aims to address performance or conduct issues through a series of escalating disciplinary actions. The specific steps of progressive discipline will be communicated to employees when necessary.</p>
    <p>Resignations: Employees who wish to resign from their position should provide written notice to their supervisor or the Human Resources department in accordance with the terms specified in their employment contract. In the case of resignations involving tuition reimbursement or relocation expenses, employees may be required to fulfill their repayment obligations as outlined in their agreement with the company. Forced resignation is not permitted, and any allegations of coerced resignation will be promptly investigated and addressed.</p>
    <p>Termination: The company reserves the right to terminate an employee's employment based on performance, conduct, violation of company policies, or other legitimate reasons. Termination may be subject to the requirements set forth in the Employment Act and any applicable laws. Employees will be provided with appropriate notice or payment in lieu of notice, as required by law.</p>
    <p>References: The company will provide references for current or former employees in accordance with applicable laws and regulations. References will be factual and limited to job-related information.</p>
    <h2>Handbook Acknowledgment</h2>
    <p>I acknowledge that I have received a copy of <span class="highlight">${data.companyName}</span> Employee Handbook. I understand that it is my responsibility to read and familiarize myself with the contents of the handbook.</p>
    <p>I further acknowledge that the policies, procedures, and guidelines outlined in the handbook are subject to change at the company's discretion. I understand that I will be notified of any updates or amendments to the handbook through appropriate channels.</p>
    <p>I understand that the information in the Employee Handbook is provided as a general guide and does not constitute a contract of employment. It is not intended to create any contractual rights or obligations, either expressed or implied, between the company and myself.</p>
    <p>I understand that failure to comply with the policies, procedures, and guidelines outlined in the Employee Handbook may result in disciplinary action, up to and including termination of employment.</p>
    <p>I agree to abide by the principles and expectations set forth in the Employee Handbook and to contribute to maintaining a positive work environment that respects the rights and dignity of all employees.</p>
    <p>Please sign and return this acknowledgment form to the Human Resources department.</p>
    <p>Thank you for your cooperation.</p>
    <p>Issued on <span class="highlight">${data.date}</span>.</p>
    <br/>
    <div style="margin-top:40px;">
      <div> ______________________ </div>
      <div>  The Employer </div>
      <div> 	______________________ </div>
      <div>  The Company Management </div>
    </div>
  </div>
</div>`;
